# Site settings
author: Marc Blanchard
title: Programming Helps You Think
header-img: img/home-bg.png
email: marcblanchard0930@gmail.com
copyright_name: Marc Blanchard
description: > # this means to ignore newlines until "baseurl:"
  Programming challenges you to think further. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcolivier0930

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
